### ISSUE TITLE
[BUG] Idena verification issue

### ISSUE THREAD

**Issue by lebraat** [passportxyz/passport#3102]
**Overview**
User (0xc5e246bADf072288Bb9e52F2E6ac8f397A1a6836 ) is receiving error when trying to verify Idena.

**Steps To Reproduce**
1. Go to 'idena'
2. Click on 'verify'
3. See error

**Observed  behavior**
User is receiving this error:
```Verification Response

To preserve your privacy, error information is not stored; please share with Gitcoin support at your discretion.

[
  {
    "code": 403,
    "error": "There was an unexpected error during verification. TypeError: Cannot read properties of undefined (reading 'state') at requestIdentityState (/usr/src/platforms/dist/commonjs/Idena/procedures/idenaSignIn.js:68:56)"
  },
  {
    "code": 403,
    "error": "There was an unexpected error during verification. TypeError: Cannot read properties of undefined (reading 'state') at requestIdentityState (/usr/src/platforms/dist/commonjs/Idena/procedures/idenaSignIn.js:68:56)"
  },
  {
    "code": 403,
    "error": "There was an unexpected error during verification. TypeError: Cannot read properties of undefined (reading 'state') at requestIdentityState (/usr/src/platforms/dist/commonjs/Idena/procedures/idenaSignIn.js:68:56)"
  }
]


**Expected behavior**
Verification works if the user has properly completed the Idena tasks. 

A normal "verification failed" if the user has not verified Stamp. 

----


We are waiting for the user to get back to us with some more information.

**Comment by Jkd-eth** [comment]
Closing this as it's covered under #3101
